version: "3.9"

services:
  activemq:
      image: apache/activemq-artemis:2.39.0-alpine
      container_name: activemq
      environment:
        - ARTEMIS_USERNAME=admin   
        - ARTEMIS_PASSWORD=admin      
        - ARTEMIS_ROLES=amq
        - ANONYMOUS_LOGIN=true
      ports:
        - "61616:61616"  # AMQP/CORE
        - "5672:5672"    # AMQP
        - "8161:8161"    # Web console
      healthcheck:
        test: [ "CMD", "bash", "-lc", "bin/artemis check node --user $ARTEMIS_USER --password $ARTEMIS_PASSWORD || exit 1" ]
        interval: 45s
        timeout: 60s
        retries: 10

      

  jms-client:
    build: 
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    container_name: jms-client
    ports:
      - "9999:9999"
    depends_on:
      - activemq
    volumes:
      - .:/jms-client  
    environment:
      AMQP_HOST: activemq
      AMQP_PORT: 5672
      AMQP_USERNAME: admin
      AMQP_PASSWORD: admin
